# Generated by Django 4.1.7 on 2023-03-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WorkStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WorkTitle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Works",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("priority", models.IntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(null=True)),
                ("plan_date", models.DateTimeField(null=True)),
                (
                    "statusid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.workstatus",
                    ),
                ),
                (
                    "workid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.worktitle",
                    ),
                ),
            ],
        ),
    ]
